### ISSUE TITLE
some maps require api key

### ISSUE THREAD

**Issue by vincent3569** [acrylian/zp_openstreetmap#14]
thunderforest* map styles require an api key ("api key required" is noticed on the map).
but there is no option for that.

**Comment by acrylian** [comment]
That must be new, I am sure I originally included only free map styles without any api key required. The problem was in my memory also that those api keys also were not the same setup for all vendors requiring keys (e.g. too many specific options…)

So I would vote to possibly throw these out…

**Comment by vincent3569** [comment]
is there a way to add other maps like IGN, Bing or Google?
and enable the choice of the maps for the user?

in fact I am interested too by OpenTopoMap (http://leaflet-extras.github.io/leaflet-providers/preview/)

**Comment by acrylian** [comment]
> OpenTopoMap

>  IGN, Bing or Google?
Bing might be possible. IGN maps I don't know at all. But the general purpose of this plugin is to use free and open map tiles and specifically not Google etc. Google is not directly possible and I don't intend to use this workaround:

> *I want to use Google Maps API tiles with Leaflet, can I do that?
The problem with Google is that its Terms of Use forbid any means of tile access other than through the Google Maps API.*
You can add the Google Maps API as a Leaflet layer with the GoogleMutant plugin. But note that the map experience will not be perfect, because Leaflet must wait for the Google Maps JS engine to load the map tiles, so you might experience glitches and lagging when using it.

https://github.com/Leaflet/Leaflet/blob/master/FAQ.md#data-providers

I don't indent to incorporate this "hack". Best stick to the GoogleMaps plugin if you want to use those.

Been a while I look at the API key part but I mean to recall that there is not general standard for this which made it a bit complicated.

I can look to incorporate this provider add on but originally didn't not on purpose to only include the free ones and those without API key required.

**Comment by acrylian** [comment]
I incorporated the leaflet-providers now and also support for those api keys.

**Comment by vincent3569** [comment]
hi
thanks for adding leaftet-providers.
As far I can see, HERE credentials works and Thunderforest too.
But, as describre here https://github.com/acrylian/zp_openstreetmap/issues/21, MapBox doesn't work, and I don't kow why.
